  # **GRADUATION THESIS**

##  **Screen Time Analysis by Generation in Türkiye Using Machine Learning**

### _Step 1: Understanding the Dataset_ ###

In [64]:
import pandas as pd
import numpy as np

In [66]:
df = pd.read_excel("screentime.xlsx")
df

,generation,gender,livingArea_type,edu_level,occupation,devices_used,main_device,avg_screenTimeHours,peak_screenTimePeriod,ScreenUse [screenUse_WorkStudy],ScreenUse [screenUse_SocialMedia],ScreenUse [screenUse_Streaming],ScreenUse [screenUse_Gaming],ScreenUse [screenUse_OnlineShopping],ScreenUse [screenUse_ReadingNews],ScreenUse_Problems,Reduce_ScreenTimeOpinion,EmotionalState_AfterUse,ScreenTime_IncreasedPandemic
0,1997–2012 (Generation Z),Female (Kadın),Metropol (Metropolitan),Lisans (Bachelor’s Degree),Öğrenci (Student),"Smartphone (Akıllı Telefon), Laptop (Dizüstü B...",Smartphone (Akıllı Telefon),8,Akşam (Evening),Her Zaman (Always),Her Zaman (Always),Sık sık (Often),Nadiren (Rarely),Bazen (Sometimes),Sık sık (Often),"Göz Yorgunluğu (Eye Strain), Uyku Sorunları (S...",Yes (Evet),4,5
1,1997–2012 (Generation Z),Female (Kadın),Metropol (Metropolitan),Lisans (Bachelor’s Degree),Öğrenci (Student),"Smartphone (Akıllı Telefon), Laptop (Dizüstü B...",Smartphone (Akıllı Telefon),4,Öğleden sonra (Afternoon),Her Zaman (Always),Her Zaman (Always),Sık sık (Often),Nadiren (Rarely),Bazen (Sometimes),Bazen (Sometimes),"Göz Yorgunluğu (Eye Strain), Baş Ağrısı (Heada...",Yes (Evet),3,5
2,1981–1996 (Generation Y),Female (Kadın),Metropol (Metropolitan),Lisans (Bachelor’s Degree),Öğretmen (Teacher),Smartphone (Akıllı Telefon),Smartphone (Akıllı Telefon),3,Akşam (Evening),Nadiren (Rarely),Sık sık (Often),Sık sık (Often),Hiçbir Zaman (Never),Sık sık (Often),Bazen (Sometimes),"Göz Yorgunluğu (Eye Strain), Baş Ağrısı (Heada...",Yes (Evet),2,5
3,1997–2012 (Generation Z),Female (Kadın),Şehir/İl merkezi (City center/Urban),Lise (High School),Öğrenci (Student),Smartphone (Akıllı Telefon),Smartphone (Akıllı Telefon),8,Öğleden sonra (Afternoon),Sık sık (Often),Her Zaman (Always),Her Zaman (Always),Sık sık (Often),Bazen (Sometimes),Nadiren (Rarely),Hiçbiri (None),No (Hayır),1,5
4,1997–2012 (Generation Z),Female (Kadın),İlçe/Kasaba (Small city/Town),Yüksek Lisans (Master’s Degree),Öğrenci (Student),Smartphone (Akıllı Telefon),Smartphone (Akıllı Telefon),6,Öğleden sonra (Afternoon),Bazen (Sometimes),Sık sık (Often),Sık sık (Often),Bazen (Sometimes),Her Zaman (Always),Bazen (Sometimes),Uyku Sorunları (Sleep Problems),Yes (Evet),5,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
312,1981–1996 (Generation Y),Male (Erkek),Metropol (Metropolitan),Yüksek Lisans (Master’s Degree),Yazılım Geliştirici (Software Developer),"Smartphone (Akıllı Telefon), Laptop (Dizüstü B...",Smartphone (Akıllı Telefon),8,"Sabah (Morning), Öğleden sonra (Afternoon), Ak...",Her Zaman (Always),Sık sık (Often),Sık sık (Often),Nadiren (Rarely),Sık sık (Often),Bazen (Sometimes),"Göz Yorgunluğu (Eye Strain), Baş Ağrısı (Heada...",Yes (Evet),5,5
313,1946–1964 (Baby Boomers),Male (Erkek),İl merkezi/Şehir (City center/Urban),İlkokul (Primary School),Emekli (Retired),Smartphone (Akıllı Telefon),Smartphone (Akıllı Telefon),5,Akşam (Evening),Hiçbir Zaman (Never),Nadiren (Rarely),Nadiren (Rarely),Hiçbir Zaman (Never),Hiçbir Zaman (Never),Sık sık (Often),"Göz Yorgunluğu (Eye Strain), Uyku Sorunları (S...",Yes (Evet),3,5
314,1981–1996 (Generation Y),Male (Erkek),Metropol (Metropolitan),Lisans (Bachelor’s Degree),Yazılım Geliştirici (Software Developer),"Smartphone (Akıllı Telefon), Laptop (Dizüstü B...",Laptop (Dizüstü Bilgisayar),10 saatten fazla (more than 10),"Sabah (Morning), Öğleden sonra (Afternoon), Ak...",Her Zaman (Always),Sık sık (Often),Sık sık (Often),Nadiren (Rarely),Bazen (Sometimes),Sık sık (Often),"Göz Yorgunluğu (Eye Strain), Uyku Sorunları (S...",Yes (Evet),5,5
315,1997–2012 (Generation Z),Male (Erkek),Metropol (Metropolitan),Lisans (Bachelor’s Degree),Öğrenci (Student),"Smartphone (Akıllı Telefon), Laptop (Dizüstü B...",Laptop (Dizüstü Bilgisayar),10 saatten fazla (more than 10),"Sabah (Morning), Öğleden sonra (Afternoon), Ak...",Her Zaman (Always),Sık sık (Often),Her Zaman (Always),Sık sık (Often),Her Zaman (Always),Bazen (Sometimes),"Göz Yorgunluğu (Eye Strain), Uyku Sorunları (S...",Yes (Evet),4,5
316,1981–1996 (Generation Y),Female (Kadın),Metropol (Metropolitan),Lisans (Bachelor’s Degree),Ev Hanımı / Housewife,Smartphone (Akıllı Telefon),Smartphone (Akıllı Telefon),5,"Akşam (Evening), Gece (Night)",Sık sık (Often),Her Zaman (Always),Hiçbir Zaman (Never),Hiçbir Zaman (Never),Bazen (Sometimes),Sık sık (Often),"Göz Yorgunluğu (Eye Strain), Baş Ağrısı (Heada...",Yes (Evet),3,5

In [68]:
df.describe()

       EmotionalState_AfterUse  ScreenTime_IncreasedPandemic
count               317.000000                    317.000000
mean                  2.870662                      4.220820
std                   1.012106                      1.125851
min                   1.000000                      1.000000
25%                   2.000000                      4.000000
50%                   3.000000                      5.000000
75%                   3.000000                      5.000000
max                   5.000000                      5.000000

In [70]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 317 entries, 0 to 316
Data columns (total 19 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   generation                            317 non-null    object
 1   gender                                317 non-null    object
 2   livingArea_type                       317 non-null    object
 3   edu_level                             317 non-null    object
 4   occupation                            317 non-null    object
 5   devices_used                          317 non-null    object
 6   main_device                           317 non-null    object
 7   avg_screenTimeHours                   317 non-null    object
 8   peak_screenTimePeriod                 317 non-null    object
 9   ScreenUse [screenUse_WorkStudy]       317 non-null    object
 10  ScreenUse [screenUse_SocialMedia]     317 non-null    object
 11  ScreenUse [screenUse_Streaming]       317 non-null    object
 12  ScreenUse [screenUse_Gaming]          317 non-null    object
 13  ScreenUse [screenUse_OnlineShopping]  317 non-null    object
 14  ScreenUse [screenUse_ReadingNews]     317 non-null    object
 15  ScreenUse_Problems                    317 non-null    object
 16  Reduce_ScreenTimeOpinion              317 non-null    object
 17  EmotionalState_AfterUse               317 non-null    int64
 18  ScreenTime_IncreasedPandemic          317 non-null    int64
dtypes: int64(2), object(17)
memory usage: 47.2+ KB

### _Step 2: Data Cleaning_

In [73]:
# Checked for missing values
print("\nMissing values per column:")
df.isnull().sum()

Missing values per column:

generation                              0
gender                                  0
livingArea_type                         0
edu_level                               0
occupation                              0
devices_used                            0
main_device                             0
avg_screenTimeHours                     0
peak_screenTimePeriod                   0
ScreenUse [screenUse_WorkStudy]         0
ScreenUse [screenUse_SocialMedia]       0
ScreenUse [screenUse_Streaming]         0
ScreenUse [screenUse_Gaming]            0
ScreenUse [screenUse_OnlineShopping]    0
ScreenUse [screenUse_ReadingNews]       0
ScreenUse_Problems                      0
Reduce_ScreenTimeOpinion                0
EmotionalState_AfterUse                 0
ScreenTime_IncreasedPandemic            0
dtype: int64

In [75]:
# Checked for duplicates
print("\nNumber of duplicate entries:")
df.duplicated().sum()

Number of duplicate entries:

2

In [78]:
print(df.columns)

Index(['generation', 'gender', 'livingArea_type', 'edu_level', 'occupation',
       'devices_used', 'main_device', 'avg_screenTimeHours',
       'peak_screenTimePeriod', 'ScreenUse [screenUse_WorkStudy]',
       'ScreenUse [screenUse_SocialMedia]', 'ScreenUse [screenUse_Streaming]',
       'ScreenUse [screenUse_Gaming]', 'ScreenUse [screenUse_OnlineShopping]',
       'ScreenUse [screenUse_ReadingNews]', 'ScreenUse_Problems',
       'Reduce_ScreenTimeOpinion', 'EmotionalState_AfterUse',
       'ScreenTime_IncreasedPandemic'],
      dtype='object')

### _Step 3: Encoding Categorical Variables_

In [80]:
# 1. One-Hot Encoding
onehot_cols = ['occupation', 'main_device', 'peak_screenTimePeriod']
df = pd.get_dummies(df, columns=onehot_cols, dtype=int)

In [82]:
print([repr(col) for col in df.columns])

["'generation'", "'gender'", "'livingArea_type'", "'edu_level'", "'devices_used'", "'avg_screenTimeHours'", "'ScreenUse [screenUse_WorkStudy]'", "'ScreenUse [screenUse_SocialMedia]'", "'ScreenUse [screenUse_Streaming]'", "'ScreenUse [screenUse_Gaming]'", "'ScreenUse [screenUse_OnlineShopping]'", "'ScreenUse [screenUse_ReadingNews]'", "'ScreenUse_Problems'", "'Reduce_ScreenTimeOpinion'", "'EmotionalState_AfterUse'", "'ScreenTime_IncreasedPandemic'", "'occupation_Akademisyen (Academician / Instructor)'", "'occupation_Destek Hizmetleri Personeli (Yemekhane, Temizlik, Güvenlik vb.) – Support Services Staff (Cafeteria, Cleaning, Security, etc.)'", "'occupation_Diğer'", "'occupation_Emekli (Retired)'", "'occupation_Ev Hanımı / Housewife'", "'occupation_Hekim (Doctor)'", "'occupation_Kamu Çalışanı / Memur (Public Sector Employee / Civil Servant)'", "'occupation_Mühendis (Engineer)'", "'occupation_Serbest Çalışan (Freelancer)'", "'occupation_Yazılım Geliştirici (Software Developer)'", "'occupation_Özel Sektör Çalışanı (Private Sector Employee)'", "'occupation_Öğrenci (Student)'", "'occupation_Öğretmen (Teacher)'", "'occupation_İşsiz  (Unemployed)'", "'main_device_Desktop (Masaüstü Bilgisayar)'", "'main_device_Laptop (Dizüstü Bilgisayar)'", "'main_device_Smart TV'", "'main_device_Smartphone (Akıllı Telefon)'", "'main_device_Tablet'", "'peak_screenTimePeriod_Akşam (Evening)'", "'peak_screenTimePeriod_Akşam (Evening), Gece (Night)'", "'peak_screenTimePeriod_Gece (Night)'", "'peak_screenTimePeriod_Gün boyu '", "'peak_screenTimePeriod_Sabah (Morning)'", "'peak_screenTimePeriod_Sabah (Morning), Akşam (Evening)'", "'peak_screenTimePeriod_Sabah (Morning), Akşam (Evening), Gece (Night)'", "'peak_screenTimePeriod_Sabah (Morning), Gece (Night)'", "'peak_screenTimePeriod_Sabah (Morning), Sabah 8 den aksam 6 ya kadar'", "'peak_screenTimePeriod_Sabah (Morning), Öğleden sonra (Afternoon)'", "'peak_screenTimePeriod_Sabah (Morning), Öğleden sonra (Afternoon), Akşam (Evening)'", "'peak_screenTimePeriod_Sabah (Morning), Öğleden sonra (Afternoon), Akşam (Evening), Gece (Night)'", "'peak_screenTimePeriod_Tüm gün '", "'peak_screenTimePeriod_genel'", "'peak_screenTimePeriod_Öğleden sonra (Afternoon)'", "'peak_screenTimePeriod_Öğleden sonra (Afternoon), '", "'peak_screenTimePeriod_Öğleden sonra (Afternoon), Akşam (Evening)'", "'peak_screenTimePeriod_Öğleden sonra (Afternoon), Akşam (Evening), Gece (Night)'", "'peak_screenTimePeriod_Öğleden sonra (Afternoon), Gece (Night)'"]

In [84]:
df.columns = df.columns.str.strip("'")

In [86]:
print(df.columns.tolist())

['generation', 'gender', 'livingArea_type', 'edu_level', 'devices_used', 'avg_screenTimeHours', 'ScreenUse [screenUse_WorkStudy]', 'ScreenUse [screenUse_SocialMedia]', 'ScreenUse [screenUse_Streaming]', 'ScreenUse [screenUse_Gaming]', 'ScreenUse [screenUse_OnlineShopping]', 'ScreenUse [screenUse_ReadingNews]', 'ScreenUse_Problems', 'Reduce_ScreenTimeOpinion', 'EmotionalState_AfterUse', 'ScreenTime_IncreasedPandemic', 'occupation_Akademisyen (Academician / Instructor)', 'occupation_Destek Hizmetleri Personeli (Yemekhane, Temizlik, Güvenlik vb.) – Support Services Staff (Cafeteria, Cleaning, Security, etc.)', 'occupation_Diğer', 'occupation_Emekli (Retired)', 'occupation_Ev Hanımı / Housewife', 'occupation_Hekim (Doctor)', 'occupation_Kamu Çalışanı / Memur (Public Sector Employee / Civil Servant)', 'occupation_Mühendis (Engineer)', 'occupation_Serbest Çalışan (Freelancer)', 'occupation_Yazılım Geliştirici (Software Developer)', 'occupation_Özel Sektör Çalışanı (Private Sector Employee)', 'occupation_Öğrenci (Student)', 'occupation_Öğretmen (Teacher)', 'occupation_İşsiz  (Unemployed)', 'main_device_Desktop (Masaüstü Bilgisayar)', 'main_device_Laptop (Dizüstü Bilgisayar)', 'main_device_Smart TV', 'main_device_Smartphone (Akıllı Telefon)', 'main_device_Tablet', 'peak_screenTimePeriod_Akşam (Evening)', 'peak_screenTimePeriod_Akşam (Evening), Gece (Night)', 'peak_screenTimePeriod_Gece (Night)', 'peak_screenTimePeriod_Gün boyu ', 'peak_screenTimePeriod_Sabah (Morning)', 'peak_screenTimePeriod_Sabah (Morning), Akşam (Evening)', 'peak_screenTimePeriod_Sabah (Morning), Akşam (Evening), Gece (Night)', 'peak_screenTimePeriod_Sabah (Morning), Gece (Night)', 'peak_screenTimePeriod_Sabah (Morning), Sabah 8 den aksam 6 ya kadar', 'peak_screenTimePeriod_Sabah (Morning), Öğleden sonra (Afternoon)', 'peak_screenTimePeriod_Sabah (Morning), Öğleden sonra (Afternoon), Akşam (Evening)', 'peak_screenTimePeriod_Sabah (Morning), Öğleden sonra (Afternoon), Akşam (Evening), Gece (Night)', 'peak_screenTimePeriod_Tüm gün ', 'peak_screenTimePeriod_genel', 'peak_screenTimePeriod_Öğleden sonra (Afternoon)', 'peak_screenTimePeriod_Öğleden sonra (Afternoon), ', 'peak_screenTimePeriod_Öğleden sonra (Afternoon), Akşam (Evening)', 'peak_screenTimePeriod_Öğleden sonra (Afternoon), Akşam (Evening), Gece (Night)', 'peak_screenTimePeriod_Öğleden sonra (Afternoon), Gece (Night)']

In [97]:
# 2. Ordinal Encoding

edu_level_map = {
    "İlkokul (Primary School)": 0,
    "Ortaokul (Middle School)": 1,
    "Lise (High School)": 2,
    "Lisans (Bachelor’s Degree)": 3,
    "Yüksek Lisans (Master’s Degree)": 4,
    "Doktora (PhD)": 5
}
df['edu_level'] = df['edu_level'].map(edu_level_map)

freq_map = {
    "Hiç": 0,
    "Nadiren": 1,
    "Bazen": 2,
    "Sık": 3,
    "Çok sık": 4
}
freq_cols = [
    'ScreenUse [screenUse_WorkStudy]',
    'ScreenUse [screenUse_SocialMedia]',
    'ScreenUse [screenUse_Streaming]',
    'ScreenUse [screenUse_Gaming]',
    'ScreenUse [screenUse_OnlineShopping]',
    'ScreenUse [screenUse_ReadingNews]'
]

freq_map = {
    "Hiç": 0,
    "Az": 1,
    "Orta": 2,
    "Çok": 3,
    "Çok Fazla": 4
}

for col in freq_cols:
    df[col] = df[col].map(freq_map)

emotion_map = {
    "Olumsuz": 0,
    "Nötr": 1,
    "Olumlu": 2
}

df['EmotionalState_AfterUse'] = df['EmotionalState_AfterUse'].map(emotion_map)

In [99]:
# 3. Label Encoding (remaining categorical columns)
from sklearn.preprocessing import LabelEncoder


label_encoders = {}

exclude_cols = onehot_cols + freq_cols + ['edu_level', 'emotionalState_AfterUse']

categorical_cols = df.select_dtypes(include='object').columns.tolist()

label_cols = [col for col in categorical_cols if col not in exclude_cols]

for col in label_cols:
    df[col] = df[col].astype(str)
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    label_encoders[col] = le
    print(f"{col} -> {list(le.classes_)}")

generation -> ['1946–1964 (Baby Boomers)', '1965–1980 (Generation X)', '1981–1996 (Generation Y)', '1997–2012 (Generation Z)']
gender -> ['Female (Kadın)', 'Male (Erkek)']
livingArea_type -> ['Kırsal alan/Köy (Rural area/Village)', 'Metropol (Metropolitan)', 'İl merkezi/Şehir (City center/Urban)', 'İlçe/Kasaba (Small city/Town)', 'Şehir/İl merkezi (City center/Urban)']
devices_used -> ['Laptop (Dizüstü Bilgisayar)', 'Smart TV', 'Smartphone (Akıllı Telefon)', 'Smartphone (Akıllı Telefon), Desktop (Masaüstü Bilgisayar)', 'Smartphone (Akıllı Telefon), Desktop (Masaüstü Bilgisayar), Smart TV', 'Smartphone (Akıllı Telefon), Laptop (Dizüstü Bilgisayar)', 'Smartphone (Akıllı Telefon), Laptop (Dizüstü Bilgisayar), Desktop (Masaüstü Bilgisayar)', 'Smartphone (Akıllı Telefon), Laptop (Dizüstü Bilgisayar), Desktop (Masaüstü Bilgisayar), Smart TV', 'Smartphone (Akıllı Telefon), Laptop (Dizüstü Bilgisayar), Smart TV', 'Smartphone (Akıllı Telefon), Laptop (Dizüstü Bilgisayar), Smart TV, Akıllı Tahta', 'Smartphone (Akıllı Telefon), Laptop (Dizüstü Bilgisayar), Tablet', 'Smartphone (Akıllı Telefon), Laptop (Dizüstü Bilgisayar), Tablet, Desktop (Masaüstü Bilgisayar)', 'Smartphone (Akıllı Telefon), Laptop (Dizüstü Bilgisayar), Tablet, Desktop (Masaüstü Bilgisayar), Smart TV', 'Smartphone (Akıllı Telefon), Laptop (Dizüstü Bilgisayar), Tablet, Smart TV', 'Smartphone (Akıllı Telefon), Smart TV', 'Smartphone (Akıllı Telefon), Smart TV, Ps', 'Smartphone (Akıllı Telefon), Tablet', 'Smartphone (Akıllı Telefon), Tablet, Desktop (Masaüstü Bilgisayar)', 'Smartphone (Akıllı Telefon), Tablet, Smart TV', 'Tablet', 'Tablet, Smart TV']
avg_screenTimeHours -> ['1', '10', '10 saatten fazla (more than 10)', '2', '3', '4', '5', '6', '7', '8', '9']
ScreenUse_Problems -> ['Baş Ağrısı (Headaches)', 'Baş Ağrısı (Headaches), Kaygı/Stres (Anxiety/Stress), Konsantrasyon Eksikliği (Lack of concentration)', 'Baş Ağrısı (Headaches), Konsantrasyon Eksikliği (Lack of concentration)', 'Göz Yorgunluğu (Eye Strain)', 'Göz Yorgunluğu (Eye Strain), Baş Ağrısı (Headaches)', 'Göz Yorgunluğu (Eye Strain), Baş Ağrısı (Headaches), Kaygı/Stres (Anxiety/Stress)', 'Göz Yorgunluğu (Eye Strain), Baş Ağrısı (Headaches), Kaygı/Stres (Anxiety/Stress), Konsantrasyon Eksikliği (Lack of concentration)', 'Göz Yorgunluğu (Eye Strain), Baş Ağrısı (Headaches), Konsantrasyon Eksikliği (Lack of concentration)', 'Göz Yorgunluğu (Eye Strain), Kaygı/Stres (Anxiety/Stress)', 'Göz Yorgunluğu (Eye Strain), Kaygı/Stres (Anxiety/Stress), Konsantrasyon Eksikliği (Lack of concentration)', 'Göz Yorgunluğu (Eye Strain), Konsantrasyon Eksikliği (Lack of concentration)', 'Göz Yorgunluğu (Eye Strain), Uyku Sorunları (Sleep Problems)', 'Göz Yorgunluğu (Eye Strain), Uyku Sorunları (Sleep Problems), Baş Ağrısı (Headaches)', 'Göz Yorgunluğu (Eye Strain), Uyku Sorunları (Sleep Problems), Baş Ağrısı (Headaches), Kaygı/Stres (Anxiety/Stress)', 'Göz Yorgunluğu (Eye Strain), Uyku Sorunları (Sleep Problems), Baş Ağrısı (Headaches), Kaygı/Stres (Anxiety/Stress), Konsantrasyon Eksikliği (Lack of concentration)', 'Göz Yorgunluğu (Eye Strain), Uyku Sorunları (Sleep Problems), Baş Ağrısı (Headaches), Konsantrasyon Eksikliği (Lack of concentration)', 'Göz Yorgunluğu (Eye Strain), Uyku Sorunları (Sleep Problems), Kaygı/Stres (Anxiety/Stress)', 'Göz Yorgunluğu (Eye Strain), Uyku Sorunları (Sleep Problems), Kaygı/Stres (Anxiety/Stress), Konsantrasyon Eksikliği (Lack of concentration)', 'Göz Yorgunluğu (Eye Strain), Uyku Sorunları (Sleep Problems), Konsantrasyon Eksikliği (Lack of concentration)', 'Hiçbiri (None)', 'Kaygı/Stres (Anxiety/Stress)', 'Kaygı/Stres (Anxiety/Stress), Konsantrasyon Eksikliği (Lack of concentration)', 'Konsantrasyon Eksikliği (Lack of concentration)', 'Konsantrasyon Eksikliği (Lack of concentration), Hiçbiri (None)', 'Uyku Sorunları (Sleep Problems)', 'Uyku Sorunları (Sleep Problems), Baş Ağrısı (Headaches)', 'Uyku Sorunları (Sleep Problems), Kaygı/Stres (Anxiety/Stress)', 'Uyku Sorunları (Sleep Problems), Kaygı/Stres (Anxiety/Stress), Konsantrasyon Eksikliği (Lack of concentration)', 'Uyku Sorunları (Sleep Problems), Konsantrasyon Eksikliği (Lack of concentration)']
Reduce_ScreenTimeOpinion -> ['No (Hayır)', 'Not sure (Emin değilim)', 'Yes (Evet)']