  # **GRADUATION THESIS**

##  **Screen Time Analysis by Generation in Türkiye Using Machine Learning**

### _Step 1: Understanding the Dataset_ ###

In [9]:
import pandas as pd
import numpy as np

In [35]:
df = pd.read_excel("screentime.xlsx")
df

,generation,sex,livingArea_type,edu_level,occupation,devices_used,main_device,avg_screenTimeHours,peak_screenTimePeriod,screenUse_WorkStudy,screenUse_SocialMedia,screenUse_Streaming,screenUse_Gaming,screenUse_OnlineShopping,screenUse_ReadingNews,screenUse_Problems,reduce_ScreenTimeOpinion,emotionalState_AfterUse,screenTime_IncreasedPandemic
0,1997–2012 (Generation Z),Female (Kadın),Metropol (Metropolitan),Lisans (Bachelor’s Degree),Öğrenci (Student),"Smartphone (Akıllı Telefon), Laptop (Dizüstü B...",Smartphone (Akıllı Telefon),8,Akşam (Evening),Her Zaman (Always),Her Zaman (Always),Sık sık (Often),Nadiren (Rarely),Bazen (Sometimes),Sık sık (Often),"Göz Yorgunluğu (Eye Strain), Uyku Sorunları (S...",Yes (Evet),4,5
1,1997–2012 (Generation Z),Female (Kadın),Metropol (Metropolitan),Lisans (Bachelor’s Degree),Öğrenci (Student),"Smartphone (Akıllı Telefon), Laptop (Dizüstü B...",Smartphone (Akıllı Telefon),4,Öğleden sonra (Afternoon),Her Zaman (Always),Her Zaman (Always),Sık sık (Often),Nadiren (Rarely),Bazen (Sometimes),Bazen (Sometimes),"Göz Yorgunluğu (Eye Strain), Baş Ağrısı (Heada...",Yes (Evet),3,5
2,1981–1996 (Generation Y),Female (Kadın),Metropol (Metropolitan),Lisans (Bachelor’s Degree),Öğretmen (Teacher),Smartphone (Akıllı Telefon),Smartphone (Akıllı Telefon),3,Akşam (Evening),Nadiren (Rarely),Sık sık (Often),Sık sık (Often),Hiçbir Zaman (Never),Sık sık (Often),Bazen (Sometimes),"Göz Yorgunluğu (Eye Strain), Baş Ağrısı (Heada...",Yes (Evet),2,5
3,1997–2012 (Generation Z),Female (Kadın),Şehir/İl merkezi (City center/Urban),Lise (High School),Öğrenci (Student),Smartphone (Akıllı Telefon),Smartphone (Akıllı Telefon),8,Öğleden sonra (Afternoon),Sık sık (Often),Her Zaman (Always),Her Zaman (Always),Sık sık (Often),Bazen (Sometimes),Nadiren (Rarely),Hiçbiri (None),No (Hayır),1,5
4,1997–2012 (Generation Z),Female (Kadın),İlçe/Kasaba (Small city/Town),Yüksek Lisans (Master’s Degree),Öğrenci (Student),Smartphone (Akıllı Telefon),Smartphone (Akıllı Telefon),6,Öğleden sonra (Afternoon),Bazen (Sometimes),Sık sık (Often),Sık sık (Often),Bazen (Sometimes),Her Zaman (Always),Bazen (Sometimes),Uyku Sorunları (Sleep Problems),Yes (Evet),5,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
312,1981–1996 (Generation Y),Male (Erkek),Metropol (Metropolitan),Yüksek Lisans (Master’s Degree),Yazılım Geliştirici (Software Developer),"Smartphone (Akıllı Telefon), Laptop (Dizüstü B...",Smartphone (Akıllı Telefon),8,"Sabah (Morning), Öğleden sonra (Afternoon), Ak...",Her Zaman (Always),Sık sık (Often),Sık sık (Often),Nadiren (Rarely),Sık sık (Often),Bazen (Sometimes),"Göz Yorgunluğu (Eye Strain), Baş Ağrısı (Heada...",Yes (Evet),5,5
313,1946–1964 (Baby Boomers),Male (Erkek),İl merkezi/Şehir (City center/Urban),İlkokul (Primary School),Emekli (Retired),Smartphone (Akıllı Telefon),Smartphone (Akıllı Telefon),5,Akşam (Evening),Hiçbir Zaman (Never),Nadiren (Rarely),Nadiren (Rarely),Hiçbir Zaman (Never),Hiçbir Zaman (Never),Sık sık (Often),"Göz Yorgunluğu (Eye Strain), Uyku Sorunları (S...",Yes (Evet),3,5
314,1981–1996 (Generation Y),Male (Erkek),Metropol (Metropolitan),Lisans (Bachelor’s Degree),Yazılım Geliştirici (Software Developer),"Smartphone (Akıllı Telefon), Laptop (Dizüstü B...",Laptop (Dizüstü Bilgisayar),10 saatten fazla (more than 10),"Sabah (Morning), Öğleden sonra (Afternoon), Ak...",Her Zaman (Always),Sık sık (Often),Sık sık (Often),Nadiren (Rarely),Bazen (Sometimes),Sık sık (Often),"Göz Yorgunluğu (Eye Strain), Uyku Sorunları (S...",Yes (Evet),5,5
315,1997–2012 (Generation Z),Male (Erkek),Metropol (Metropolitan),Lisans (Bachelor’s Degree),Öğrenci (Student),"Smartphone (Akıllı Telefon), Laptop (Dizüstü B...",Laptop (Dizüstü Bilgisayar),10 saatten fazla (more than 10),"Sabah (Morning), Öğleden sonra (Afternoon), Ak...",Her Zaman (Always),Sık sık (Often),Her Zaman (Always),Sık sık (Often),Her Zaman (Always),Bazen (Sometimes),"Göz Yorgunluğu (Eye Strain), Uyku Sorunları (S...",Yes (Evet),4,5
316,1981–1996 (Generation Y),Female (Kadın),Metropol (Metropolitan),Lisans (Bachelor’s Degree),Ev Hanımı / Housewife,Smartphone (Akıllı Telefon),Smartphone (Akıllı Telefon),5,"Akşam (Evening), Gece (Night)",Sık sık (Often),Her Zaman (Always),Hiçbir Zaman (Never),Hiçbir Zaman (Never),Bazen (Sometimes),Sık sık (Often),"Göz Yorgunluğu (Eye Strain), Baş Ağrısı (Heada...",Yes (Evet),3,5

In [37]:
df.describe()

       emotionalState_AfterUse  screenTime_IncreasedPandemic
count               317.000000                    317.000000
mean                  2.870662                      4.220820
std                   1.012106                      1.125851
min                   1.000000                      1.000000
25%                   2.000000                      4.000000
50%                   3.000000                      5.000000
75%                   3.000000                      5.000000
max                   5.000000                      5.000000

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 317 entries, 0 to 316
Data columns (total 19 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   generation                    317 non-null    object
 1   sex                           317 non-null    object
 2   livingArea_type               317 non-null    object
 3   edu_level                     317 non-null    object
 4   occupation                    317 non-null    object
 5   devices_used                  317 non-null    object
 6   main_device                   317 non-null    object
 7   avg_screenTimeHours           317 non-null    object
 8   peak_screenTimePeriod         317 non-null    object
 9   screenUse_WorkStudy           317 non-null    object
 10  screenUse_SocialMedia         317 non-null    object
 11  screenUse_Streaming           317 non-null    object
 12  screenUse_Gaming              317 non-null    object
 13  screenUse_OnlineShopping      317 non-null    object
 14  screenUse_ReadingNews         317 non-null    object
 15  screenUse_Problems            317 non-null    object
 16  reduce_ScreenTimeOpinion      317 non-null    object
 17  emotionalState_AfterUse       317 non-null    int64
 18  screenTime_IncreasedPandemic  317 non-null    int64
dtypes: int64(2), object(17)
memory usage: 47.2+ KB